# Generated by Django 5.1.4 on 2024-12-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('html', 'HTML'), ('js', 'JavaScript')], max_length=30),
        ),
    ]
